Repository php-rust-tools/parser, pull requests merged in 2022-12, with the labels that each got.

#154 lexer&parser: full heredoc/nowdoc support
  meta/dump
  meta/snapshot
  src/lexer/byte_string.rs
  src/lexer/error.rs
  src/lexer/mod.rs
  src/lexer/state.rs
  src/lexer/token.rs
  src/parser/ast.rs
  src/parser/mod.rs
  tests/0224/ast.txt
  tests/0224/code.php
  tests/0224/tokens.txt
  tests/0225/ast.txt
  tests/0225/code.php
  tests/0225/tokens.txt
  tests/0226/code.php
  tests/0226/lexer-error.txt
  tests/0227/code.php
  tests/0227/lexer-error.txt
  tests/0228/ast.txt
  tests/0228/code.php
  tests/0228/tokens.txt
  tests/0229/ast.txt
  tests/0229/code.php
  tests/0229/tokens.txt
  tests/0230/ast.txt
  tests/0230/code.php
  tests/0230/tokens.txt
  tests/0231/ast.txt
  tests/0231/code.php
  tests/0231/tokens.txt
  tests/0232/ast.txt
  tests/0232/code.php
  tests/0232/tokens.txt
  tests/0233/code.php
  tests/0233/lexer-error.txt
  tests/0234/code.php
  tests/0234/lexer-error.txt
  tests/0235/ast.txt
  tests/0235/code.php
  tests/0235/tokens.txt
Labels: parser

#188 parser: separate infix operations into new expressions
  src/parser/ast/mod.rs
  src/parser/ast/operators.rs
  src/parser/expressions.rs
  tests/fixtures/0007/ast.txt
  tests/fixtures/0008/ast.txt
  tests/fixtures/0009/ast.txt
  tests/fixtures/0010/ast.txt
  tests/fixtures/0011/ast.txt
  tests/fixtures/0012/ast.txt
  tests/fixtures/0017/ast.txt
  tests/fixtures/0018/ast.txt
  tests/fixtures/0019/ast.txt
  tests/fixtures/0020/ast.txt
  tests/fixtures/0021/ast.txt
  tests/fixtures/0034/ast.txt
  tests/fixtures/0038/ast.txt
  tests/fixtures/0178/ast.txt
  tests/fixtures/0183/ast.txt
  tests/fixtures/0184/ast.txt
  tests/fixtures/0193/ast.txt
  tests/fixtures/0194/ast.txt
  tests/fixtures/0195/ast.txt
  tests/fixtures/0196/ast.txt
  tests/fixtures/0197/ast.txt
  tests/fixtures/0218/ast.txt
  tests/fixtures/0220/ast.txt
  tests/fixtures/0223/ast.txt
  tests/fixtures/0237/ast.txt
  tests/fixtures/0238/ast.txt
  tests/fixtures/0243/ast.txt
  tests/fixtures/0244/ast.txt
  tests/fixtures/0256/ast.txt
  tests/fixtures/0259/ast.txt
  tests/fixtures/0260/ast.txt
  tests/fixtures/0261/ast.txt
  tests/fixtures/0262/ast.txt
  tests/fixtures/0269/ast.txt
  tests/fixtures/0273/ast.txt
  tests/fixtures/0274/ast.txt
  tests/fixtures/0280/ast.txt
  tests/fixtures/0280/code.php
Labels: parser

#216 chore: update list of forbidden methods on enum
  src/parser/internal/enums.rs
  tests/fixtures/0301-enum-call/ast.txt
  tests/fixtures/0301-enum-call/parser-error.txt
  tests/fixtures/0302-enum-call-static/ast.txt
  tests/fixtures/0302-enum-call-static/parser-error.txt
  tests/fixtures/0303-enum-invoke/ast.txt
  tests/fixtures/0303-enum-invoke/parser-error.txt
  tests/fixtures/0308-enum-clone/code.php
  tests/fixtures/0308-enum-clone/parser-error.txt
  tests/fixtures/0309-enum-debug-info/code.php
  tests/fixtures/0309-enum-debug-info/parser-error.txt
  tests/fixtures/0310-enum-isset/code.php
  tests/fixtures/0310-enum-isset/parser-error.txt
  tests/fixtures/0311-enum-set-state/code.php
  tests/fixtures/0311-enum-set-state/parser-error.txt
  tests/fixtures/0312-enum-tostring/code.php
  tests/fixtures/0312-enum-tostring/parser-error.txt
  tests/fixtures/0313-enum-unset/code.php
  tests/fixtures/0313-enum-unset/parser-error.txt
  tests/fixtures/0314-php-issue-10083/ast.txt
  tests/fixtures/0314-php-issue-10083/code.php
Labels: bug

#247 chore: improve error messages and formatting
  Justfile
  src/parser/error.rs
  src/parser/internal/classes.rs
  src/parser/internal/enums.rs
  src/parser/internal/functions.rs
  src/parser/internal/interfaces.rs
  src/parser/internal/parameters.rs
  src/parser/internal/properties.rs
  src/parser/internal/traits.rs
  tests/fixtures/0002/error.txt
  tests/fixtures/0086/error.txt
  tests/fixtures/0087/error.txt
  tests/fixtures/0111/error.txt
  tests/fixtures/0112/error.txt
  tests/fixtures/0120/error.txt
  tests/fixtures/0124/error.txt
  tests/fixtures/0125/error.txt
  tests/fixtures/0126/error.txt
  tests/fixtures/0128/error.txt
  tests/fixtures/0129/error.txt
  tests/fixtures/0146/error.txt
  tests/fixtures/0147/error.txt
  tests/fixtures/0148/error.txt
  tests/fixtures/0152/error.txt
  tests/fixtures/0154/error.txt
  tests/fixtures/0156/error.txt
  tests/fixtures/0165/error.txt
  tests/fixtures/0166/error.txt
  tests/fixtures/0167/error.txt
  tests/fixtures/0168/error.txt
  tests/fixtures/0169/error.txt
  tests/fixtures/0170/error.txt
  tests/fixtures/0171/error.txt
  tests/fixtures/0172/error.txt
  tests/fixtures/0173/error.txt
  tests/fixtures/0210/error.txt
  tests/fixtures/0263/error.txt
  tests/fixtures/0264/error.txt
  tests/fixtures/0265/error.txt
  tests/fixtures/0286-reserved-type-name/error.txt
  tests/fixtures/0287-reserved-label-name/error.txt
  tests/fixtures/0288-reserved-label-name/error.txt
  tests/fixtures/0291-reserved-const/error.txt
  tests/fixtures/0297-enum-serialize/error.txt
  tests/fixtures/0298-enum-unserialize/error.txt
  tests/fixtures/0299-enum-get/error.txt
  tests/fixtures/0300-enum-set/error.txt
  tests/fixtures/0304-enum-dtor/error.txt
  tests/fixtures/0305-enum-sleep/error.txt
  tests/fixtures/0306-enum-wakeup/error.txt
  tests/fixtures/0308-enum-clone/error.txt
  tests/fixtures/0309-enum-debug-info/error.txt
  tests/fixtures/0310-enum-isset/error.txt
  tests/fixtures/0311-enum-set-state/error.txt
  tests/fixtures/0312-enum-tostring/error.txt
  tests/fixtures/0313-enum-unset/error.txt
Labels: enhancement

#256 feature: recognise __COMPILER_HALT_OFFSET__ as a magic constant
  src/lexer/mod.rs
  src/lexer/token.rs
  src/parser/ast/mod.rs
  src/parser/expressions.rs
  src/parser/internal/identifiers.rs
  tests/fixtures/0329-compiler-halt-offset/ast.txt
  tests/fixtures/0329-compiler-halt-offset/code.php
Labels: enhancement

#260 fix: allow reserved keywords in namespaces
  src/parser/internal/arrays.rs
  src/parser/internal/identifiers.rs
  tests/fixtures/0101/ast.txt
  tests/fixtures/0102/ast.txt
  tests/fixtures/0329/ast.txt
  tests/fixtures/0329/code.php
Labels: bug

#262 fix: logical or is tokenized as pipe
  src/lexer/mod.rs
  tests/fixtures/0330-pipe/ast.txt
  tests/fixtures/0330-pipe/code.php
Labels: bug
